### ISSUE TITLE
RNWinRTTestApp doesn't build using command line

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/react-native-winrt#164]
Currently building the sample requires using Visual Studio.

When building on the command line with:

```cmd
npm install
npx react-native run-windows --logging
```

I see the following error in the output:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.App
XPackage.Targets(3496,5): error APPX0108: The certificate specified has expired. For more information about renewing ce
rtificates, see http://go.microsoft.com/fwlink/?LinkID=241478. [C:\Users\angzhang\source\repos\react-native-winrt2\samp
les\RNWinRTTestApp\windows\RNWinRTTestApp\RNWinRTTestApp.vcxproj]
```

Either need to address the issue or document what extra steps are needed to build the sample with command line only

**Comment by dunhor** [comment]
Oh, that's right. For some reason I was thinking that I renewed this cert, however it was the test app whose cert I renewed. Such a shame that certs are even required still...
