### ISSUE TITLE
Question: Is this module also usable for own WinRT components

### ISSUE THREAD

**Issue by smw-wagnerma** [microsoft/react-native-winrt#206]
It is not so clear for me, if this module also works for own WinRT components or only for windows SDK provided? The background is, I am investigating ways for doing the business logic in rust and use react-native for the front end. It seems now posssible to do a WinRT component in rust (https://github.com/Alovchin91/winrt-component-rs), this will improve when the windows-rs projects improves. So, is it possible to provide an interface to business logic in rust through a WinRT component and use it with this module in react native?

**Comment by dunhor** [comment]
Yes, this is possible. In fact, that's what the tests do. They build a WinRT dll [here](https://github.com/microsoft/react-native-winrt/tree/main/tests/RnWinRTTests/windows/TestComponent), which gets referenced by the turbo module [here](https://github.com/microsoft/react-native-winrt/blob/6029375d66ed6903ad3f9e9ceabeb0993d26e1b3/tests/RnWinRTTests/windows/WinRTTurboModule/WinRTTurboModule.vcxproj#L153) and then included in the projection [here](https://github.com/microsoft/react-native-winrt/blob/6029375d66ed6903ad3f9e9ceabeb0993d26e1b3/tests/RnWinRTTests/windows/WinRTTurboModule/WinRTTurboModule.vcxproj#L25). Of course, you don't need to build the dll as part of your project - just referencing the WinMD when invoking `rnwinrt.exe` is enough, however the exact msbuild/project configuration will differ from this example.
